services:

    nginx:
        image: nginx:latest
        volumes:
            - './:/var/www'
            - './_docker/nginx/conf.d:/etc/nginx/conf.d'
        ports:
            - "49154:80"
        depends_on:
            - app
        container_name: content-microservice-nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - phpredisadmin
            - phpmyadmin
            - cache
            - db
        container_name: content-microservice

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: contentMicroservice
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "49155:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: content-microservice-db

    cache:
        image: redis:latest
        restart: always
        volumes:
            - ./tmp/cache:/var/lib/redis
        ports:
            - "49156:6379"
        container_name: content-microservice-cache

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: content-microservice-php-my-admin
        ports:
            - "49157:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306

    phpredisadmin:
        image: erikdubbelboer/phpredisadmin
        container_name: content-microservice-php-redis-admin
        ports:
            - "49158:80"
        environment:
            REDIS_1_HOST: cache
            REDIS_1_PORT: 6379
            REDIS_1_AUTH: null
        depends_on:
            - cache
